name = "EDM Checkout"
client_id = "c468873c6697ae10cd1f7d7463e34251"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[access_scopes]
scopes = "read_orders,read_customers,read_products"

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home",
  "https://redirect.shopify.com/oauth/redirect-from-cli",
  "http://localhost:4000/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false
