api_version = "2025-07"
uid = "e40458fc-6220-d187-8aa5-ea56c26d685c96d52697"

[[extensions]]
type = "ui_extension"
name = "Cédula / NIT — Factura electrónica"
handle = "cedula-field"

  [[extensions.targeting]]
  module = "./src/Checkout.tsx"
  target = "purchase.checkout.contact.render-after"
